// Generated by CoffeeScript 1.8.0

/*
#===========================================================================================================



 .d8888b.   .d88888b.  888888b.          d8888     .d8888b.  888      8888888 8888888888 888b    888 88888888888
d88P  Y88b d88P" "Y88b 888  "88b        d88888    d88P  Y88b 888        888   888        8888b   888     888
Y88b.      888     888 888  .88P       d88P888    888    888 888        888   888        88888b  888     888
 "Y888b.   888     888 8888888K.      d88P 888    888        888        888   8888888    888Y88b 888     888
    "Y88b. 888     888 888  "Y88b    d88P  888    888        888        888   888        888 Y88b888     888
      "888 888     888 888    888   d88P   888    888    888 888        888   888        888  Y88888     888
Y88b  d88P Y88b. .d88P 888   d88P  d8888888888    Y88b  d88P 888        888   888        888   Y8888     888
 "Y8888P"   "Y88888P"  8888888P"  d88P     888     "Y8888P"  88888888 8888888 8888888888 888    Y888     888



#===========================================================================================================
 */

(function() {
  var TRM, alert, badge, debug, help, info, new_sio_client, njs_path, rpr, sio_client, urge, warn, whisper,
    __slice = [].slice;

  njs_path = require('path');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'ソバ/SERVER';

  info = TRM.get_logger('info', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  urge = TRM.get_logger('urge', badge);

  whisper = TRM.get_logger('whisper', badge);

  help = TRM.get_logger('help', badge);

  new_sio_client = require('socket.io-client');

  sio_client = new_sio_client('http://0.0.0.0:3000/');


  /* NB difference to server side:
    * no `connection` event, but `connect`
    * no `socket` argument; use `sio_client` to listen for events.
   */

  sio_client.on('connect', function() {
    return help("client: connect");
  });

  sio_client.on('connect_error', function() {
    return help("client: connect_error");
  });

  sio_client.on('connect_timeout', function() {
    return help("client: connect_timeout");
  });

  sio_client.on('reconnect', function() {
    return help("client: reconnect");
  });

  sio_client.on('reconnect_attempt', function() {
    return help("client: reconnect_attempt");
  });

  sio_client.on('reconnect_error', function() {
    return help("client: reconnect_error");
  });

  sio_client.on('reconnect_failed', function() {
    return help("client: reconnect_failed");
  });

  sio_client.on('reconnecting', function() {
    return help("client: reconnecting");
  });

  sio_client.on('news', function() {
    var message;
    message = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return info('news:', message);
  });

  sio_client.on('connect', function() {
    var P;
    P = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    sio_client.emit('helo');
    return sio_client.emit('news', 'everyone should know', {
      foo: 42
    });
  });

  sio_client.on('helo', (function(_this) {
    return function(data) {
      return help('updated-client-id', data['client-id']);
    };
  })(this));

}).call(this);
