// Generated by CoffeeScript 1.8.0

/*
#===========================================================================================================



 .d8888b.   .d88888b.  888888b.          d8888     .d8888b.  888      8888888 8888888888 888b    888 88888888888
d88P  Y88b d88P" "Y88b 888  "88b        d88888    d88P  Y88b 888        888   888        8888b   888     888
Y88b.      888     888 888  .88P       d88P888    888    888 888        888   888        88888b  888     888
 "Y888b.   888     888 8888888K.      d88P 888    888        888        888   8888888    888Y88b 888     888
    "Y88b. 888     888 888  "Y88b    d88P  888    888        888        888   888        888 Y88b888     888
      "888 888     888 888    888   d88P   888    888    888 888        888   888        888  Y88888     888
Y88b  d88P Y88b. .d88P 888   d88P  d8888888888    Y88b  d88P 888        888   888        888   Y8888     888
 "Y8888P"   "Y88888P"  8888888P"  d88P     888     "Y8888P"  88888888 8888888 8888888888 888    Y888     888



#===========================================================================================================
 */

(function() {
  var $, CND, D, D2, SOBAC, TEXT, alert, badge, debug, f, help, info, new_socket, njs_fs, njs_path, rpr, socket, urge, warn, whisper, wrap_as_socket_stream,
    __slice = [].slice;

  njs_path = require('path');

  njs_fs = require('fs');

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'ソバ/CLIENT';

  info = CND.get_logger('info', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  help = CND.get_logger('help', badge);

  TEXT = require('coffeenode-text');


  /* https://github.com/loveencounterflow/pipedreams */

  D = require('pipedreams');

  D2 = require('pipedreams2');

  $ = D.remit.bind(D);


  /* https://github.com/nkzawa/socket.io-stream */

  wrap_as_socket_stream = require('socket.io-stream');

  new_socket = require('socket.io-client');

  socket = new_socket('http://0.0.0.0:3000/');


  /* **NB** difference to server side:
    * no `connection` event, but `connect`
    * no `socket` argument; use `socket` to listen for events.
   */

  socket.on('connect', function() {
    return help("client: connect");
  });

  socket.on('connect_error', function() {
    return help("client: connect_error");
  });

  socket.on('connect_timeout', function() {
    return help("client: connect_timeout");
  });

  socket.on('reconnect', function() {
    return help("client: reconnect");
  });

  socket.on('reconnect_attempt', function() {
    return help("client: reconnect_attempt");
  });

  socket.on('reconnect_error', function() {
    return help("client: reconnect_error");
  });

  socket.on('reconnect_failed', function() {
    return help("client: reconnect_failed");
  });

  socket.on('reconnecting', function() {
    return help("client: reconnecting");
  });

  socket.on('connect', function() {
    var P, count, limit, skip_count;
    P = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    help("SoBa ソバ Client running on Node v" + process.versions['node']);

    /* TAINT get address from connection / options */
    help("SoBa ソバ Client connected to http://0.0.0.0:3000/");
    socket.emit('helo');
    socket.emit('news', 'everyone should know', {
      foo: 42
    });
    count = 20;
    skip_count = 100;
    limit = skip_count + count;
    return SOBAC.dump(socket, {
      take: limit,
      skip: skip_count,
      format: 'one-by-one',
      prefix: 'os|reading'
    }, function() {
      var P;
      P = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return debug('©fTwiH', P);
    });
  });

  f = function(socket) {
    var idx, idx_txt, key, value, _i, _results;
    _results = [];
    for (idx = _i = 0; _i <= 20; idx = ++_i) {
      idx_txt = TEXT.flush_right(idx, 3, '0');
      key = "key-" + idx_txt;
      value = "value-#" + idx_txt;
      _results.push(socket.emit('put', [key, value]));
    }
    return _results;
  };

  this.dump = function(me, settings, handler) {
    var CHR, glyph, glyphs, idx, input, stream, stream_settings, _i, _len;
    CHR = require('coffeenode-chr');
    glyphs = CHR.chrs_from_text('〇一二三四五六七八九');
    input = D2.create_throughstream();
    idx = -1;
    input.pipe($(function(chr, send) {
      var key, query;
      idx += +1;
      key = "so|glyph:" + glyph + "|pod:$value|";
      query = {
        eq: key
      };
      return send(['query', idx, query]);
    })).pipe(D2.$show());
    for (_i = 0, _len = glyphs.length; _i < _len; _i++) {
      glyph = glyphs[_i];
      input.write(glyph);
    }
    stream_settings = {
      'encoding': 'utf-8',
      'decodeStrings': true,
      'objectMode': true
    };
    stream = wrap_as_socket_stream.createStream(stream_settings);
    if (settings == null) {
      settings = {};
    }
    if (settings['take'] == null) {
      settings['take'] = 10;
    }
    if (settings['format'] == null) {
      settings['format'] = 'one-by-one';
    }

    /* me[ '%socket' ] */
    (wrap_as_socket_stream(me)).emit('dump', stream, settings);

    /* TAINT using `split` as an expedient; should use streaming JSON decoder */
    return stream.pipe(D2.$split()).pipe($((function(_this) {
      return function(line, send) {
        if ((line != null) && line.length > 0) {
          return send(JSON.parse(line));
        }
      };
    })(this))).pipe(D2.$collect()).pipe($((function(_this) {
      return function(events, send) {
        var event, _j, _len1, _results;
        CND.shuffle(events, 0.2);
        _results = [];
        for (_j = 0, _len1 = events.length; _j < _len1; _j++) {
          event = events[_j];
          _results.push(send(event));
        }
        return _results;
      };
    })(this))).pipe($((function(_this) {
      return function(event, send) {
        var key, tail, type, value, _ref;
        type = event[0], tail = 2 <= event.length ? __slice.call(event, 1) : [];
        if (type === 'batch') {
          idx = tail[0], (_ref = tail[1], key = _ref.key, value = _ref.value);
          help(idx, key);
        }
        return send(event);
      };
    })(this))).pipe(D.$on_end((function(_this) {
      return function(send, end) {
        return process.exit();
      };
    })(this)));
  };

  this.test_dense_sort = function(me) {
    var input;
    input = D.create_throughstream();
    input.pipe($((function(_this) {
      return function(event, send) {
        var idx, letter, tail, type;
        type = event[0], tail = 2 <= event.length ? __slice.call(event, 1) : [];
        if (type === 'batch') {
          idx = tail[0], letter = tail[1];
          whisper(idx, letter);
        }
        return send(event);
      };
    })(this))).pipe(D2.$dense_sort(1, 0, function(_arg) {
      var efficiency, event_count, max_buffer_size, percentage;
      event_count = _arg[0], max_buffer_size = _arg[1];
      percentage = (max_buffer_size / event_count * 100).toFixed(2);
      efficiency = (1 - max_buffer_size / event_count).toFixed(2);
      return info("of " + event_count + " elements, up to " + max_buffer_size + " (" + percentage + "%) had to be buffered;\nefficiency: " + efficiency);
    })).pipe($((function(_this) {
      return function(event, send) {
        var idx, letter, tail, type;
        type = event[0], tail = 2 <= event.length ? __slice.call(event, 1) : [];
        if (type === 'batch') {
          idx = tail[0], letter = tail[1];
          help(idx, letter);
        }
        return send(event);
      };
    })(this))).pipe(D.$on_end((function(_this) {
      return function(send, end) {
        return process.exit();
      };
    })(this)));
    input.write(['batch', 0, 'A']);
    input.write(['batch', 2, 'C']);
    input.write(['batch', 4, 'E']);
    input.write(['batch', 5, 'F']);
    input.write(['batch', 1, 'B']);
    input.write(['batch', 3, 'D']);
    return input.end();
  };

  socket.on('helo', (function(_this) {
    return function(data) {
      return help('updated-client-id', data['client-id']);
    };
  })(this));

  SOBAC = this;

}).call(this);
